name: 'Paige Holland- Artist '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80546
title: Paige Holland Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9dfec'
    - '#e79c00'
    - '#cc5000'
    - '#007f93'
    - '#64812f'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
