name: 'Paige Holland- Artist '
favicon: null
layout_spectrum: 0.9354620627127588
typography_spectrum: 0.8057596795260906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8331789660733193
  lightness: 0.8434767671860754
  saturation: 0.05722893914207816
  rhythmicContrast: 0.8246426701080054
purpose: []
